baseURL = "https://sensorgnome.org"
languageCode = "en-us"
title = "Sensorgnome Site"
defaultContentLanguage = "en"
theme = "vanilla-bootstrap-hugo-theme"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Status"
    pre = "activity"
    url = "/status/"
    weight = 2
  [[menu.nav]]
    name = "About"
    pre = "info"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "Docs"
    pre = "help-circle"
    url = "/docs/"
    weight = 4
  [[menu.nav]]
    name = "Source"
    pre = "github"
    url = "/source/"
    weight = 5

[params]
  includeBootstrapJs = true

# Needed to render links to direct SGs.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Sensorgnome"
  footerText = "[sensorgnome-website](https://github.com/sensorgnome-org/sensorgnome-website) uses [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
